<?php

/**
 * AI Agent detail pages – one page per agent.
 * Routes: /ai-agents/{slug}. SEO-friendly with unique title, meta, breadcrumbs, and structured data.
 */

return [
    'dr-amani' => [
        'name' => 'Dr. Amani',
        'niche' => 'Clinic / Hospital',
        'industry' => 'Healthcare & Wellness',
        'short_description' => 'AI agent for clinics and hospitals: appointment booking, prescription reminders, symptom triage, lab results, and insurance verification on WhatsApp and web chat.',
        'meta_description' => 'Dr. Amani AI agent for clinics and hospitals in Tanzania. Appointment booking, triage, lab notifications, insurance verification. WhatsApp and web chat.',
        'meta_keywords' => 'clinic AI bot Tanzania, hospital appointment bot, healthcare WhatsApp bot, patient triage AI',
        'capabilities' => ['Appointment booking', 'Prescription refill reminders', 'Symptom triage', 'Lab result notifications', 'Doctor availability', 'Insurance verification'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'fitcoach' => [
        'name' => 'FitCoach',
        'niche' => 'Gym / Fitness Studio',
        'industry' => 'Healthcare & Wellness',
        'short_description' => 'Gym and fitness studio AI: class booking, membership status, workout plans, trainer scheduling, attendance, and nutrition tips.',
        'meta_description' => 'FitCoach AI for gyms and fitness studios. Class booking, membership, trainer scheduling, attendance. WhatsApp and web chat.',
        'meta_keywords' => 'gym booking bot, fitness studio AI, class scheduling WhatsApp',
        'capabilities' => ['Class booking', 'Membership status', 'Workout plans', 'Trainer scheduling', 'Attendance tracking', 'Nutrition tips'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'zenspa' => [
        'name' => 'ZenSpa',
        'niche' => 'Spa / Wellness Center',
        'industry' => 'Healthcare & Wellness',
        'short_description' => 'Spa and wellness AI: treatment booking, package recommendations, loyalty points, therapist preferences, and post-treatment care.',
        'meta_description' => 'ZenSpa AI for spas and wellness centers. Treatment booking, packages, loyalty, therapist preferences. WhatsApp and web chat.',
        'meta_keywords' => 'spa booking bot, wellness center AI, treatment scheduling',
        'capabilities' => ['Treatment booking', 'Package recommendations', 'Loyalty points', 'Therapist preferences', 'Post-treatment care tips'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'dentacare' => [
        'name' => 'DentaCare',
        'niche' => 'Dental Clinic',
        'industry' => 'Healthcare & Wellness',
        'short_description' => 'Dental clinic AI: appointment scheduling, treatment reminders, insurance queries, post-procedure care, and emergency triage.',
        'meta_description' => 'DentaCare AI for dental clinics. Appointments, reminders, insurance, post-procedure care. WhatsApp and web chat.',
        'meta_keywords' => 'dental clinic bot, dentist appointment AI, oral care WhatsApp bot',
        'capabilities' => ['Appointment scheduling', 'Treatment reminders', 'Insurance queries', 'Post-procedure care', 'Emergency triage'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'pharmbot' => [
        'name' => 'PharmBot',
        'niche' => 'Pharmacy',
        'industry' => 'Healthcare & Wellness',
        'short_description' => 'Pharmacy AI: prescription refills, drug interaction checks, stock availability, delivery tracking, and dosage reminders.',
        'meta_description' => 'PharmBot AI for pharmacies. Prescription refills, drug interactions, stock, delivery tracking. WhatsApp and web chat.',
        'meta_keywords' => 'pharmacy bot Tanzania, prescription refill AI, drug interaction check',
        'capabilities' => ['Prescription refill requests', 'Drug interaction checks', 'Stock availability', 'Delivery tracking', 'Dosage reminders'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'hotelconcierge' => [
        'name' => 'HotelConcierge',
        'niche' => 'Hotel / Resort',
        'industry' => 'Hospitality & Travel',
        'short_description' => 'Hotel and resort AI: room booking, check-in/out, room service, local recommendations, spa booking, and billing.',
        'meta_description' => 'HotelConcierge AI for hotels and resorts. Bookings, check-in, room service, spa, billing. WhatsApp and web chat.',
        'meta_keywords' => 'hotel concierge bot, resort booking AI, Tanzania hospitality bot',
        'capabilities' => ['Room booking', 'Check-in/out', 'Room service ordering', 'Local recommendations', 'Spa/pool booking', 'Billing', 'Complaint handling'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'safariguide' => [
        'name' => 'SafariGuide',
        'niche' => 'Tour Operator',
        'industry' => 'Hospitality & Travel',
        'short_description' => 'Tour operator AI: tour booking, itinerary management, pickup scheduling, weather alerts, payments, and visa reminders.',
        'meta_description' => 'SafariGuide AI for tour operators in Tanzania. Tour booking, itineraries, pickups, payments. WhatsApp and web chat.',
        'meta_keywords' => 'safari booking bot Tanzania, tour operator AI, travel WhatsApp bot',
        'capabilities' => ['Tour booking', 'Itinerary management', 'Pickup scheduling', 'Weather alerts', 'Payment processing', 'Visa/passport reminders'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'airlink' => [
        'name' => 'AirLink',
        'niche' => 'Airline / Charter',
        'industry' => 'Hospitality & Travel',
        'short_description' => 'Airline AI: flight booking, check-in, seat selection, baggage tracking, delay notifications, and rebooking.',
        'meta_description' => 'AirLink AI for airlines and charters. Flight booking, check-in, baggage, delays, rebooking. WhatsApp and web chat.',
        'meta_keywords' => 'airline bot, flight booking AI, charter booking WhatsApp',
        'capabilities' => ['Flight booking', 'Check-in', 'Seat selection', 'Baggage tracking', 'Delay notifications', 'Rebooking', 'Loyalty miles'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'cruisemate' => [
        'name' => 'CruiseMate',
        'niche' => 'Cruise Line',
        'industry' => 'Hospitality & Travel',
        'short_description' => 'Cruise line AI: shore excursion booking, dining reservations, onboard activities, and cabin service requests.',
        'meta_description' => 'CruiseMate AI for cruise lines. Excursions, dining, onboard activities, cabin service. WhatsApp and web chat.',
        'meta_keywords' => 'cruise booking bot, shore excursion AI, cruise concierge',
        'capabilities' => ['Shore excursion booking', 'Dining reservations', 'Onboard activity scheduling', 'Cabin service requests'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'shopassist' => [
        'name' => 'ShopAssist',
        'niche' => 'Retail Store / E-commerce',
        'industry' => 'Retail & E-Commerce',
        'short_description' => 'Retail and e-commerce AI: product search, stock checks, orders, delivery tracking, returns, and recommendations.',
        'meta_description' => 'ShopAssist AI for retail and e-commerce. Product search, orders, delivery, returns. WhatsApp and web chat.',
        'meta_keywords' => 'retail chatbot Tanzania, e-commerce AI, order tracking bot',
        'capabilities' => ['Product search', 'Stock checks', 'Order placement', 'Delivery tracking', 'Returns/exchanges', 'Personalized recommendations'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'freshmart' => [
        'name' => 'FreshMart',
        'niche' => 'Grocery / Supermarket',
        'industry' => 'Retail & E-Commerce',
        'short_description' => 'Grocery AI: shopping list ordering, delivery scheduling, weekly specials, recipe suggestions, and loyalty management.',
        'meta_description' => 'FreshMart AI for groceries and supermarkets. Ordering, delivery, specials, recipes. WhatsApp and web chat.',
        'meta_keywords' => 'grocery bot Tanzania, supermarket ordering AI, delivery scheduling bot',
        'capabilities' => ['Shopping list ordering', 'Delivery scheduling', 'Weekly specials', 'Recipe suggestions', 'Loyalty card management', 'Reorder favorites'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'stylebot' => [
        'name' => 'StyleBot',
        'niche' => 'Fashion / Boutique',
        'industry' => 'Retail & E-Commerce',
        'short_description' => 'Fashion and boutique AI: size recommendations, outfit suggestions, new arrivals, wishlist, and personal shopper assistance.',
        'meta_description' => 'StyleBot AI for fashion and boutiques. Size tips, outfits, new arrivals, wishlist. WhatsApp and web chat.',
        'meta_keywords' => 'fashion chatbot, boutique AI, personal shopper bot',
        'capabilities' => ['Size recommendations', 'Outfit suggestions', 'New arrival alerts', 'Wishlist management', 'Personal shopper assistance', 'Fitting room booking'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'autoparts' => [
        'name' => 'AutoParts',
        'niche' => 'Auto Parts Store',
        'industry' => 'Retail & E-Commerce',
        'short_description' => 'Auto parts AI: part lookup by vehicle, compatibility checks, stock availability, order tracking, and mechanic referrals.',
        'meta_description' => 'AutoParts AI for auto parts stores. Part lookup, compatibility, stock, tracking. WhatsApp and web chat.',
        'meta_keywords' => 'auto parts bot, vehicle part lookup AI, mechanic referral',
        'capabilities' => ['Part lookup by vehicle model', 'Compatibility checks', 'Stock availability', 'Order tracking', 'Mechanic referrals'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'edubot' => [
        'name' => 'EduBot',
        'niche' => 'School / University',
        'industry' => 'Education',
        'short_description' => 'School and university AI: class schedules, grades, assignment reminders, fee notifications, teacher communication, and events.',
        'meta_description' => 'EduBot AI for schools and universities. Schedules, grades, fees, teacher communication. WhatsApp and web chat.',
        'meta_keywords' => 'school bot Tanzania, university chatbot, fee payment bot',
        'capabilities' => ['Class schedules', 'Grade checks', 'Assignment reminders', 'Fee payment notifications', 'Teacher communication', 'Event alerts'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'tutorlink' => [
        'name' => 'TutorLink',
        'niche' => 'Tutoring Center',
        'industry' => 'Education',
        'short_description' => 'Tutoring AI: session booking, tutor matching, progress reports, homework help queue, and parent updates.',
        'meta_description' => 'TutorLink AI for tutoring centers. Session booking, tutor matching, progress, parent updates. WhatsApp and web chat.',
        'meta_keywords' => 'tutoring bot, tutor booking AI, homework help chatbot',
        'capabilities' => ['Session booking', 'Tutor matching', 'Progress reports', 'Homework help queue', 'Parent updates'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'drivingschool' => [
        'name' => 'DrivingSchool',
        'niche' => 'Driving School',
        'industry' => 'Education',
        'short_description' => 'Driving school AI: lesson booking, instructor assignment, theory test prep, license status, and payment tracking.',
        'meta_description' => 'DrivingSchool AI for driving schools. Lesson booking, instructors, theory prep, license status. WhatsApp and web chat.',
        'meta_keywords' => 'driving school bot Tanzania, lesson booking AI, license application bot',
        'capabilities' => ['Lesson booking', 'Instructor assignment', 'Theory test preparation', 'License application status', 'Payment tracking'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'propertypal' => [
        'name' => 'PropertyPal',
        'niche' => 'Real Estate Agency',
        'industry' => 'Real Estate & Property',
        'short_description' => 'Real estate AI: property search, viewing scheduling, mortgage calculator, document collection, and offer submission.',
        'meta_description' => 'PropertyPal AI for real estate agencies. Property search, viewings, mortgage calculator. WhatsApp and web chat.',
        'meta_keywords' => 'real estate bot Tanzania, property search AI, viewing scheduling bot',
        'capabilities' => ['Property search by criteria', 'Viewing scheduling', 'Mortgage calculator', 'Document collection', 'Offer submission'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'tenanthub' => [
        'name' => 'TenantHub',
        'niche' => 'Property Management',
        'industry' => 'Real Estate & Property',
        'short_description' => 'Property management AI: rent reminders, maintenance requests, lease queries, visitor management, and community notices.',
        'meta_description' => 'TenantHub AI for property management. Rent reminders, maintenance, lease queries. WhatsApp and web chat.',
        'meta_keywords' => 'property management bot, tenant communication AI, rent reminder bot',
        'capabilities' => ['Rent reminders', 'Maintenance requests', 'Lease queries', 'Visitor management', 'Community notices'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'hosthelper' => [
        'name' => 'HostHelper',
        'niche' => 'Short-Term Rental',
        'industry' => 'Real Estate & Property',
        'short_description' => 'Short-term rental AI: check-in instructions, house rules, local tips, issue reporting, checkout reminders, and reviews.',
        'meta_description' => 'HostHelper AI for short-term rentals. Check-in, house rules, issues, reviews. WhatsApp and web chat.',
        'meta_keywords' => 'short-term rental bot, Airbnb style AI, guest communication',
        'capabilities' => ['Self check-in instructions', 'House rules', 'Local recommendations', 'Issue reporting', 'Checkout reminders', 'Review prompts'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'garagebot' => [
        'name' => 'GarageBot',
        'niche' => 'Auto Workshop / Garage',
        'industry' => 'Automotive',
        'short_description' => 'Garage and workshop AI: service booking, repair status, cost estimates, parts availability, and pickup notifications.',
        'meta_description' => 'GarageBot AI for auto workshops and garages. Service booking, repair status, estimates. WhatsApp and web chat.',
        'meta_keywords' => 'garage booking bot Tanzania, auto repair AI, service status bot',
        'capabilities' => ['Service booking', 'Repair status updates', 'Cost estimates', 'Parts availability', 'Pickup notifications', 'Service history'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'carwash' => [
        'name' => 'CarWash',
        'niche' => 'Car Wash',
        'industry' => 'Automotive',
        'short_description' => 'Car wash AI: slot booking, membership plans, loyalty stamps, service selection, queue updates, and payment.',
        'meta_description' => 'CarWash AI for car wash businesses. Slot booking, memberships, queue updates. WhatsApp and web chat.',
        'meta_keywords' => 'car wash booking bot, loyalty stamps AI, queue bot',
        'capabilities' => ['Slot booking', 'Membership plans', 'Loyalty stamps', 'Service selection', 'Queue position updates', 'Payment'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'dealerbot' => [
        'name' => 'DealerBot',
        'niche' => 'Car Dealership',
        'industry' => 'Automotive',
        'short_description' => 'Car dealership AI: test drive booking, financing calculator, trade-in valuation, inventory search, and service scheduling.',
        'meta_description' => 'DealerBot AI for car dealerships. Test drives, financing, trade-in, inventory. WhatsApp and web chat.',
        'meta_keywords' => 'car dealership bot, test drive booking AI, trade-in valuation bot',
        'capabilities' => ['Test drive booking', 'Financing calculator', 'Trade-in valuation', 'Inventory search', 'Service scheduling'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'loanguide' => [
        'name' => 'LoanGuide',
        'niche' => 'Microfinance / SACCO',
        'industry' => 'Financial Services',
        'short_description' => 'Microfinance and SACCO AI: loan status, repayment reminders, balance inquiries, savings goals, and document submission.',
        'meta_description' => 'LoanGuide AI for microfinance and SACCOS in Tanzania. Loan status, repayments, balance. WhatsApp and web chat.',
        'meta_keywords' => 'SACCO bot Tanzania, microfinance chatbot, loan status AI',
        'capabilities' => ['Loan application status', 'Repayment reminders', 'Balance inquiries', 'Savings goal tracking', 'Document submission'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'insurebot' => [
        'name' => 'InsureBot',
        'niche' => 'Insurance Agency',
        'industry' => 'Financial Services',
        'short_description' => 'Insurance AI: policy queries, claims filing, premium reminders, coverage recommendations, and emergency assistance.',
        'meta_description' => 'InsureBot AI for insurance agencies. Policies, claims, premiums, coverage. WhatsApp and web chat.',
        'meta_keywords' => 'insurance bot Tanzania, claims filing AI, policy query chatbot',
        'capabilities' => ['Policy queries', 'Claims filing', 'Premium reminders', 'Coverage recommendations', 'Emergency assistance'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'accountantai' => [
        'name' => 'AccountantAI',
        'niche' => 'Accounting Firm',
        'industry' => 'Financial Services',
        'short_description' => 'Accounting firm AI: invoice status, tax deadline reminders, document upload, expense categorization, and quarterly summaries.',
        'meta_description' => 'AccountantAI for accounting firms. Invoices, tax reminders, documents, expenses. WhatsApp and web chat.',
        'meta_keywords' => 'accounting bot, tax reminder AI, invoice status chatbot',
        'capabilities' => ['Invoice status', 'Tax deadline reminders', 'Document upload', 'Expense categorization', 'Quarterly summaries'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'farmlink' => [
        'name' => 'FarmLink',
        'niche' => 'Agricultural Supplier',
        'industry' => 'Food & Agriculture',
        'short_description' => 'Agricultural supplier AI: input ordering, market prices, weather alerts, agronomist consultation, and delivery tracking.',
        'meta_description' => 'FarmLink AI for agricultural suppliers in Tanzania. Inputs, prices, weather, delivery. WhatsApp and web chat.',
        'meta_keywords' => 'agriculture bot Tanzania, farm input ordering AI, market prices bot',
        'capabilities' => ['Input ordering (seeds, fertilizer)', 'Market prices', 'Weather alerts', 'Agronomist consultation', 'Delivery tracking'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'cateringbot' => [
        'name' => 'CateringBot',
        'niche' => 'Catering Company',
        'industry' => 'Food & Agriculture',
        'short_description' => 'Catering AI: menu selection, event booking, headcount, dietary requirements, invoicing, and tasting scheduling.',
        'meta_description' => 'CateringBot AI for catering companies. Menus, events, headcount, dietary needs. WhatsApp and web chat.',
        'meta_keywords' => 'catering bot, event catering AI, menu selection chatbot',
        'capabilities' => ['Menu selection', 'Event booking', 'Headcount management', 'Dietary requirements', 'Invoice/payment', 'Tasting scheduling'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'bakerybot' => [
        'name' => 'BakeryBot',
        'niche' => 'Bakery',
        'industry' => 'Food & Agriculture',
        'short_description' => 'Bakery AI: custom cake ordering, flavor and size selection, pickup scheduling, event packages, and reorder favorites.',
        'meta_description' => 'BakeryBot AI for bakeries. Custom cakes, pickup, event packages. WhatsApp and web chat.',
        'meta_keywords' => 'bakery bot, custom cake ordering AI, bakery WhatsApp',
        'capabilities' => ['Custom cake ordering', 'Flavor/size selection', 'Pickup scheduling', 'Event packages', 'Reorder favorites'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'legalassist' => [
        'name' => 'LegalAssist',
        'niche' => 'Law Firm',
        'industry' => 'Professional Services',
        'short_description' => 'Law firm AI: consultation booking, case status, document submission, billing queries, and court date reminders.',
        'meta_description' => 'LegalAssist AI for law firms. Consultations, case status, documents, billing. WhatsApp and web chat.',
        'meta_keywords' => 'law firm bot Tanzania, legal consultation AI, case status chatbot',
        'capabilities' => ['Consultation booking', 'Case status updates', 'Document submission', 'Billing queries', 'Court date reminders'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'recruitbot' => [
        'name' => 'RecruitBot',
        'niche' => 'Recruitment Agency',
        'industry' => 'Professional Services',
        'short_description' => 'Recruitment AI: job matching, interview scheduling, application status, document collection, and onboarding checklist.',
        'meta_description' => 'RecruitBot AI for recruitment agencies. Job matching, interviews, applications. WhatsApp and web chat.',
        'meta_keywords' => 'recruitment bot, job matching AI, interview scheduling chatbot',
        'capabilities' => ['Job matching', 'Interview scheduling', 'Application status', 'Document collection', 'Onboarding checklist'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'eventpro' => [
        'name' => 'EventPro',
        'niche' => 'Event Management',
        'industry' => 'Professional Services',
        'short_description' => 'Event management AI: venue booking, vendor coordination, RSVP tracking, timeline management, and budget updates.',
        'meta_description' => 'EventPro AI for event management. Venues, vendors, RSVP, timeline. WhatsApp and web chat.',
        'meta_keywords' => 'event management bot, venue booking AI, RSVP chatbot',
        'capabilities' => ['Venue booking', 'Vendor coordination', 'Guest RSVP tracking', 'Timeline management', 'Budget updates'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'courierbot' => [
        'name' => 'CourierBot',
        'niche' => 'Delivery / Courier Service',
        'industry' => 'Logistics & Transport',
        'short_description' => 'Courier and delivery AI: pickup scheduling, live tracking, delivery confirmation, pricing calculator, and complaint handling.',
        'meta_description' => 'CourierBot AI for delivery and courier services. Pickups, tracking, pricing. WhatsApp and web chat.',
        'meta_keywords' => 'courier bot Tanzania, delivery tracking AI, pickup scheduling bot',
        'capabilities' => ['Pickup scheduling', 'Live tracking', 'Delivery confirmation', 'Pricing calculator', 'Complaint handling'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'fleetmanager' => [
        'name' => 'FleetManager',
        'niche' => 'Fleet / Transport Company',
        'industry' => 'Logistics & Transport',
        'short_description' => 'Fleet and transport AI: driver assignment, route optimization, fuel tracking, maintenance alerts, and customer ETAs.',
        'meta_description' => 'FleetManager AI for fleet and transport companies. Drivers, routes, fuel, maintenance. WhatsApp and web chat.',
        'meta_keywords' => 'fleet management bot, transport AI Tanzania, driver assignment chatbot',
        'capabilities' => ['Driver assignment', 'Route optimization', 'Fuel tracking', 'Maintenance alerts', 'Customer ETAs'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'parkingbot' => [
        'name' => 'ParkingBot',
        'niche' => 'Parking Facility',
        'industry' => 'Logistics & Transport',
        'short_description' => 'Parking facility AI: spot reservation, entry/exit management, payment, monthly passes, and availability check.',
        'meta_description' => 'ParkingBot AI for parking facilities. Reservations, entry/exit, payments. WhatsApp and web chat.',
        'meta_keywords' => 'parking bot, spot reservation AI, parking payment chatbot',
        'capabilities' => ['Spot reservation', 'Entry/exit management', 'Payment processing', 'Monthly pass management', 'Availability check'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'civicbot' => [
        'name' => 'CivicBot',
        'niche' => 'Municipal / County Government',
        'industry' => 'Government & NGO',
        'short_description' => 'Municipal AI: permit applications, bill payments (water, property tax), complaints, service status, and public notices.',
        'meta_description' => 'CivicBot AI for municipal and county government. Permits, bills, complaints. WhatsApp and web chat.',
        'meta_keywords' => 'government bot Tanzania, permit application AI, civic services chatbot',
        'capabilities' => ['Permit applications', 'Bill payments (water, property tax)', 'Complaint filing', 'Service status tracking', 'Public notices'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
    'aidlink' => [
        'name' => 'AidLink',
        'niche' => 'NGO / Humanitarian',
        'industry' => 'Government & NGO',
        'short_description' => 'NGO and humanitarian AI: beneficiary registration, distribution scheduling, feedback collection, case management, and resource requests.',
        'meta_description' => 'AidLink AI for NGOs and humanitarian organizations. Registration, distribution, feedback. WhatsApp and web chat.',
        'meta_keywords' => 'NGO bot Tanzania, humanitarian AI, beneficiary registration chatbot',
        'capabilities' => ['Beneficiary registration', 'Distribution scheduling', 'Feedback collection', 'Case management', 'Resource requests'],
        'channels' => ['WhatsApp', 'Web chat', 'API'],
    ],
];
