<?php

/**
 * Product detail pages – Tanzania market focus.
 * Each product has its own detail page at /products/{slug}.
 * Features and copy are tailored for banks, MFIs, SACCOS, and enterprises in Tanzania.
 */

return [
    'collection-solution' => [
        'title' => 'Collection Solution (Pay by Link)',
        'short_description' => 'Digital payment collection via secure links. Accept M-Pesa, Airtel Money, Tigo Pesa, and bank payments for loans, invoices, and bills—with one integration.',
        'meta_description' => 'Pay by Link and payment collection for Tanzania. M-Pesa, Airtel Money, Tigo Pesa, bank integration. Loan repayments, invoices, BillPay-style control numbers.',
        'meta_keywords' => 'pay by link Tanzania, payment collection, M-Pesa collection, Airtel Money, payment links, loan repayment, Tanzania payment gateway',
        'icon' => 'link',
        'features' => [
            ['title' => 'Secure payment links', 'description' => 'Generate unique links per invoice or loan repayment. Share via SMS, email, or WhatsApp. Customers pay without creating accounts.'],
            ['title' => 'Multi-provider support', 'description' => 'Accept M-Pesa, Tigo Pesa, Airtel Money, HaloPesa, and bank channels (SIM banking, internet banking, Wakala agents) through one platform.'],
            ['title' => 'BillPay & control numbers', 'description' => 'Issue one-time or recurring control numbers for utilities, fees, and subscriptions. Compatible with Tanzania’s BillPay and PSP ecosystem.'],
            ['title' => 'Instant confirmation', 'description' => 'Real-time payment notifications and automatic reconciliation with your core banking or loan system.'],
            ['title' => 'BOT-compliant', 'description' => 'Designed for licensed PSPs and banks. Supports KYC, AML, and audit trails required by Bank of Tanzania.'],
        ],
        'faqs' => [
            ['q' => 'How do customers pay using Pay by Link?', 'a' => 'You generate a link or control number per transaction. The customer opens the link or pays via M-Pesa/bank using the number. Funds are credited to your account and your system is updated in real time.'],
            ['q' => 'Which mobile money providers are supported?', 'a' => 'We integrate with M-Pesa (Vodacom), Tigo Pesa, Airtel Money, and HaloPesa, as well as bank channels including CRDB SIM Banking and agent networks.'],
        ],
    ],
    'channels-reconciliation' => [
        'title' => 'Channels Reconciliation System',
        'short_description' => 'Automated multi-channel reconciliation for banks. Core banking, mobile money, ATMs, POS, and digital channels—one audit-ready view.',
        'meta_description' => 'Bank reconciliation software Tanzania. Multi-channel reconciliation for core banking, mobile money, ATM, POS. BOT audit-ready reporting.',
        'meta_keywords' => 'bank reconciliation Tanzania, multi-channel reconciliation, mobile money reconciliation, core banking, ATM reconciliation',
        'icon' => 'balance-scale',
        'features' => [
            ['title' => 'Multi-channel aggregation', 'description' => 'Reconcile core banking, mobile money (M-Pesa, Airtel, Tigo), ATMs, POS, agency banking, and digital channels in one system.'],
            ['title' => 'Automated matching', 'description' => 'Rule-based matching and exception handling. Reduce manual effort and close gaps faster with clear audit trails.'],
            ['title' => 'EOD and regulatory readiness', 'description' => 'Support for end-of-day (EOD) runs and regulatory reporting. Aligns with BOT and internal audit requirements.'],
            ['title' => 'Exception management', 'description' => 'Track breaks, disputes, and reversals. Assign ownership and escalate with SLA tracking.'],
            ['title' => 'Tanzania payment rails', 'description' => 'Aware of TISS, TIPS, TACH, and mobile money settlement cycles used in Tanzania.'],
        ],
        'faqs' => [
            ['q' => 'What channels can we reconcile?', 'a' => 'Core banking, mobile money (all major MNOs), ATMs, POS, agent networks, internet banking, and third-party fintech channels—all in one reconciliation engine.'],
            ['q' => 'Is it suitable for BOT examinations?', 'a' => 'Yes. The system maintains full audit trails, supports regulatory reporting, and helps demonstrate control over settlement and reconciliation.'],
        ],
    ],
    'tanqr-merchant-management' => [
        'title' => 'TanQR Merchant Management',
        'short_description' => 'Unified merchant payment platform for Tanzania’s TAN-QR standard. One QR for all networks—M-Pesa, Airtel Money, Tigo Pesa, and banks.',
        'meta_description' => 'TAN-QR merchant platform Tanzania. BOT-compliant QR payments, static and dynamic QR, M-Pesa Airtel Tigo bank. Merchant management and settlement.',
        'meta_keywords' => 'TAN-QR Tanzania, TanQR merchant, QR code payments Tanzania, BOT QR standard, merchant payments',
        'icon' => 'qrcode',
        'features' => [
            ['title' => 'TAN-QR compliant', 'description' => 'Built to Bank of Tanzania’s national QR standard (National Payment Systems Act). One QR works with all licensed providers.'],
            ['title' => 'Static and dynamic QR', 'description' => 'Static QR for fixed locations (shops, kiosks); dynamic QR for exact amounts (e-commerce, bills). Customer scans and pays from any app.'],
            ['title' => 'Universal acceptance', 'description' => 'Customers pay with M-Pesa, Airtel Money, Tigo Pesa, or bank apps—no separate codes per provider.'],
            ['title' => 'Settlement and reporting', 'description' => 'Unified settlement and merchant statements. Clear transaction logs and reconciliation for accounting and audits.'],
            ['title' => 'Financial inclusion', 'description' => 'Low-cost acceptance for micro and small businesses. No need for expensive POS terminals; smartphone and QR suffice.'],
        ],
        'faqs' => [
            ['q' => 'What is TAN-QR?', 'a' => 'TAN-QR (Tanzania Quick Response Code) is the national QR payment standard set by the Bank of Tanzania. One QR code lets customers pay using any participating mobile money or bank app.'],
            ['q' => 'Do we need different QRs for M-Pesa and Airtel?', 'a' => 'No. With TAN-QR, a single QR works for all supported providers, simplifying signage and reconciliation for merchants.'],
        ],
    ],
    'salary-advance-management' => [
        'title' => 'Salary Advance Management',
        'short_description' => 'Automated salary advance platform. Issue advances tied to payroll with automatic deductions—for employers, banks, and payroll providers in Tanzania.',
        'meta_description' => 'Salary advance software Tanzania. Employer and bank salary advance, payroll-linked deductions, instant disbursement, M-Pesa bank integration.',
        'meta_keywords' => 'salary advance Tanzania, earned wage access, payroll advance, employer advance, salary loan',
        'icon' => 'wallet',
        'features' => [
            ['title' => 'Payroll-linked advances', 'description' => 'Configure advance limits and rules by employer. Deductions are applied automatically at payday from salary or via TACH/standing instructions.'],
            ['title' => 'Instant disbursement', 'description' => 'Disburse to bank accounts or mobile money (M-Pesa, Airtel Money) for same-day access.'],
            ['title' => 'Employer and bank models', 'description' => 'Support employer-funded advances or bank-funded salary advance products with clear repayment and fee handling.'],
            ['title' => 'Limit and eligibility rules', 'description' => 'Define max advance as % of salary, frequency caps, and tenure. Integrate with HR/payroll for eligibility.'],
            ['title' => 'Compliance and reporting', 'description' => 'Audit trail, interest/fee disclosure, and reporting for internal and regulatory use.'],
        ],
        'faqs' => [
            ['q' => 'Who can use this—employers or banks?', 'a' => 'Both. Employers can offer advances as a benefit with payroll deduction; banks can offer salary advance loans with automatic repayment from employer or salary account.'],
            ['q' => 'How is repayment collected?', 'a' => 'Repayment can be via payroll deduction, standing order, or mobile money—depending on your integration with payroll and payment rails (e.g. TACH, M-Pesa).'],
        ],
    ],
    'vehicle-financing-platform' => [
        'title' => 'Vehicle Financing Platform',
        'short_description' => 'End-to-end vehicle loan management. Applications, credit scoring, collateral tracking, and repayments—with TRA integration for Tanzania.',
        'meta_description' => 'Vehicle financing software Tanzania. Auto loan management, collateral tracking, TRA integration, credit scoring, repayment collection.',
        'meta_keywords' => 'vehicle financing Tanzania, auto loan system, car loan management, TRA motor vehicle',
        'icon' => 'car',
        'features' => [
            ['title' => 'Loan origination', 'description' => 'Digital applications, document capture, and workflow from application to disbursement.'],
            ['title' => 'Collateral management', 'description' => 'Register and track vehicles as collateral. Link to TRA and other registries where applicable.'],
            ['title' => 'Credit assessment', 'description' => 'Integrate with credit bureaus and internal scoring for vehicle finance decisions.'],
            ['title' => 'Repayment and collections', 'description' => 'Schedules, reminders, and collection via mobile money or bank. Track arrears and recovery.'],
            ['title' => 'TRA integration', 'description' => 'Support for verification and compliance with Tanzania Revenue Authority motor vehicle requirements.'],
        ],
        'faqs' => [
            ['q' => 'Can we link to TRA for vehicle data?', 'a' => 'The platform is designed to integrate with TRA and similar registries for collateral verification and compliance, subject to your integration agreements.'],
        ],
    ],
    'account-opening' => [
        'title' => 'Account Opening (Remote & Branch)',
        'short_description' => 'Digital KYC and account opening. Remote or in-branch with NIDA verification, biometrics, and instant account activation for Tanzania.',
        'meta_description' => 'Digital account opening Tanzania. NIDA verification, biometric KYC, remote and branch onboarding. Banks and MFIs.',
        'meta_keywords' => 'account opening Tanzania, NIDA KYC, digital onboarding, biometric verification, remote account opening',
        'icon' => 'user-plus',
        'features' => [
            ['title' => 'NIDA integration', 'description' => 'Real-time verification against the National Identification Authority. Capture name, DOB, address, photo, and biometrics as per NIDA API.'],
            ['title' => 'Remote and branch', 'description' => 'Same workflow for in-branch (tablet/kiosk) and remote (mobile/web). Reduce branch time and support digital acquisition.'],
            ['title' => 'Biometric verification', 'description' => 'Fingerprint and face capture for identity verification and fraud prevention.'],
            ['title' => 'Instant activation', 'description' => 'Once KYC is complete, accounts can be activated immediately and linked to mobile money or cards.'],
            ['title' => 'Audit and compliance', 'description' => 'Full audit trail for BOT and AML requirements. Document storage and versioning.'],
        ],
        'faqs' => [
            ['q' => 'How does NIDA verification work?', 'a' => 'The system calls NIDA (or an approved gateway) with the national ID number and receives verified identity data. It is used by major banks in Tanzania for KYC.'],
            ['q' => 'Can customers open accounts from home?', 'a' => 'Yes. Remote account opening is supported with NIDA verification and biometric capture where applicable, subject to your risk and compliance policies.'],
        ],
    ],
    'microfinance-management-system' => [
        'title' => 'Microfinance Management System',
        'short_description' => 'Complete MFI software for Tanzania. Group and individual loans, flat rate, declining balance, Islamic finance. TCDC and BOT aligned.',
        'meta_description' => 'Microfinance software Tanzania. MFI management, group loans, individual loans, TCDC BOT compliant, mobile money, reporting.',
        'meta_keywords' => 'microfinance software Tanzania, MFI system, group lending, TCDC compliant, BOT microfinance',
        'icon' => 'hand-holding-usd',
        'features' => [
            ['title' => 'Group and individual lending', 'description' => 'Manage group loans (VICOBA-style), solidarity groups, and individual micro-loans with flexible products.'],
            ['title' => 'Interest methods', 'description' => 'Flat rate, declining balance, and Islamic (Murabaha) options. Align with local practice and regulation.'],
            ['title' => 'Savings and shares', 'description' => 'Member savings, share capital, and voluntary deposits with interest or dividend handling.'],
            ['title' => 'TCDC and BOT alignment', 'description' => 'Reporting and processes that support compliance with Tanzania Cooperative Development Commission and Bank of Tanzania where applicable.'],
            ['title' => 'Mobile and USSD', 'description' => 'Optional mobile money integration, USSD, and agent channels for disbursement and collection in Tanzania.'],
        ],
        'faqs' => [
            ['q' => 'Is the system approved by TCDC?', 'a' => 'The system is designed to meet TCDC and sector requirements for digital record-keeping and reporting. Specific certification can be discussed with TCDC.'],
            ['q' => 'Can we offer Islamic microfinance?', 'a' => 'Yes. The product supports Islamic finance modules (e.g. Murabaha) alongside conventional products.'],
        ],
    ],
    'saccos-management-system' => [
        'title' => 'SACCOS Management System',
        'short_description' => 'End-to-end SACCO software. Member savings, shares, loans, dividends, and regulatory reporting. TCDC and BOT compliant for Tanzania.',
        'meta_description' => 'SACCO software Tanzania. Member management, savings, loans, shares, dividends. TCDC BOT compliant, audit and reporting.',
        'meta_keywords' => 'SACCO software Tanzania, SACCO management, TCDC, cooperative software, member loans savings',
        'icon' => 'users-cog',
        'features' => [
            ['title' => 'Member lifecycle', 'description' => 'Registration, KYC, share capital, savings accounts, and loan products in one member-centric system.'],
            ['title' => 'Loans and dividends', 'description' => 'Loan application, approval, disbursement, repayment, and dividend calculation and distribution.'],
            ['title' => 'TCDC and BOT reporting', 'description' => 'Returns and reports aligned with Tanzania Cooperative Development Commission and Bank of Tanzania expectations.'],
            ['title' => 'Audit and reconciliation', 'description' => 'Day-end reconciliation, audit trails, and controls suitable for regulators and auditors.'],
            ['title' => 'Web and mobile', 'description' => 'Branch and back-office plus optional member-facing web/USSD/mobile for transparency and self-service.'],
        ],
        'faqs' => [
            ['q' => 'Does it support TCDC reporting?', 'a' => 'Yes. The system is built to support the reporting and operational standards expected by TCDC for SACCOS in Tanzania.'],
            ['q' => 'Can members check balances and loans online?', 'a' => 'Optional member portals (web/USSD/app) can be added so members view shares, savings, and loan status.'],
        ],
    ],
    'saccos-members-portal' => [
        'title' => 'SACCOS Members Portal',
        'short_description' => 'Web portal for SACCO members. View shares, savings, loans, statements, and make requests—anywhere, anytime. TCDC-aligned for Tanzanian SACCOS.',
        'meta_description' => 'SACCO member portal Tanzania. Members view shares, savings, loans, statements, and submit requests online. TCDC-aligned, secure, for Tanzanian SACCOS.',
        'meta_keywords' => 'SACCO member portal Tanzania, members portal, SACCO self-service, cooperative member portal, TCDC SACCO',
        'icon' => 'desktop',
        'features' => [
            ['title' => 'Shares and savings', 'description' => 'Members see real-time share capital, savings balances, and transaction history in one dashboard.'],
            ['title' => 'Loans and statements', 'description' => 'View active loans, repayment schedules, and download statements. Request loan statements and payment history.'],
            ['title' => 'Requests and applications', 'description' => 'Submit loan applications, withdrawal requests, and other member requests through the portal with tracking.'],
            ['title' => 'Secure access', 'description' => 'Login with member ID and password. Optional OTP or PIN for sensitive actions. Audit trail for member activity.'],
            ['title' => 'TCDC-aligned', 'description' => 'Designed for Tanzanian SACCOS with reporting and workflows that support TCDC and cooperative best practices.'],
        ],
        'faqs' => [
            ['q' => 'Can members use it on their phone?', 'a' => 'Yes. The portal is responsive—members can access it from any browser on desktop, tablet, or mobile.'],
            ['q' => 'How does it connect to our SACCO system?', 'a' => 'The Members Portal integrates with your core SACCO management system (e.g. ZIMA SACCOS Management System) so data is always up to date.'],
        ],
    ],
    'saccos-members-mobile-app' => [
        'title' => 'SACCOS Members Mobile Application',
        'short_description' => 'Mobile app for SACCO members. Check shares, savings, loans, and make payments or requests on the go. iOS and Android for Tanzania.',
        'meta_description' => 'SACCO member app Tanzania. Mobile app for members: shares, savings, loans, statements, payments. iOS and Android. TCDC-aligned for Tanzanian SACCOS.',
        'meta_keywords' => 'SACCO member app Tanzania, SACCO mobile app, members app, cooperative app, SACCO self-service mobile',
        'icon' => 'mobile-alt',
        'features' => [
            ['title' => 'On-the-go access', 'description' => 'Members check shares, savings, and loan balances from their smartphone. Push notifications for repayments and dividends.'],
            ['title' => 'Statements and history', 'description' => 'View and download statements, repayment history, and contribution records in the app.'],
            ['title' => 'Payments and requests', 'description' => 'Make loan repayments via mobile money (M-Pesa, Airtel Money, Tigo Pesa), submit requests, and track status.'],
            ['title' => 'iOS and Android', 'description' => 'Native or cross-platform app available on App Store and Google Play for maximum member reach in Tanzania.'],
            ['title' => 'Secure and compliant', 'description' => 'Secure login, encrypted data, and design aligned with TCDC and SACCO best practices for member-facing channels.'],
        ],
        'faqs' => [
            ['q' => 'Do members need internet all the time?', 'a' => 'The app works best with internet for real-time data. Offline viewing of cached statements can be supported depending on the build.'],
            ['q' => 'Can we brand it for our SACCO?', 'a' => 'Yes. The app can be white-labelled with your SACCO name, logo, and colours for a consistent member experience.'],
        ],
    ],
    'vicoba-integration' => [
        'title' => 'VICOBA Integration',
        'short_description' => 'Connect Village Community Banks to formal banking. Digitize group savings, loans, and member records with mobile money in Tanzania.',
        'meta_description' => 'VICOBA digitization Tanzania. Link savings groups to banks, mobile money, digital loans, member records. Financial inclusion.',
        'meta_keywords' => 'VICOBA Tanzania, village community bank, savings group digitization, mobile money group, financial inclusion',
        'icon' => 'hands-helping',
        'features' => [
            ['title' => 'Group savings and loans', 'description' => 'Digitize group contributions, loans, and repayments. Replace paper books with digital records and approval workflows.'],
            ['title' => 'Bank and MNO linkage', 'description' => 'Connect groups to bank accounts or mobile money (M-Pesa, Airtel Money) for deposits, withdrawals, and disbursements.'],
            ['title' => 'Member records', 'description' => 'Member profiles, attendance, and transaction history. Support for group leaders and field officers.'],
            ['title' => 'Transparency', 'description' => 'Shared view of group balance, loan status, and history to build trust and reduce disputes.'],
            ['title' => 'Financial inclusion', 'description' => 'Designed for women, youth, and rural groups—aligned with national financial inclusion goals and partner programmes.'],
        ],
        'faqs' => [
            ['q' => 'How do groups get access to banking?', 'a' => 'Groups can be linked to a bank (e.g. group account) or use mobile money for collections and disbursements. The platform supports both models.'],
            ['q' => 'Can loans be approved on the phone?', 'a' => 'Yes. Group leaders can receive requests and approve loans via app or USSD, with funds sent to members via mobile money or bank.'],
        ],
    ],
    'investment-groups-platform' => [
        'title' => 'Investment Groups Platform',
        'short_description' => 'Digital platform for investment groups (vikundi vya uwekezaji). Group savings, investments, profit-sharing, and transparent reporting in Tanzania.',
        'meta_description' => 'Investment group software Tanzania. Vikundi vya uwekezaji, group savings, profit sharing, transparent reporting, chama management.',
        'meta_keywords' => 'investment group Tanzania, vikundi vya uwekezaji, chama software, group investment, profit sharing',
        'icon' => 'chart-line',
        'features' => [
            ['title' => 'Group savings and contributions', 'description' => 'Track regular contributions, rounds, and payouts. Replace manual books with digital records.'],
            ['title' => 'Investment tracking', 'description' => 'Record group investments and returns. Allocate profits according to agreed rules.'],
            ['title' => 'Transparent reporting', 'description' => 'Members see balances, contributions, and profit share. Build trust and reduce conflict.'],
            ['title' => 'Mobile-friendly', 'description' => 'Leaders and members can view and transact via web or mobile in Swahili and English.'],
            ['title' => 'Compliance support', 'description' => 'Audit trail and reporting to support group governance and any regulatory expectations.'],
        ],
        'faqs' => [
            ['q' => 'Is this for chamas and investment clubs?', 'a' => 'Yes. The platform is designed for informal and formal investment groups, including vikundi vya uwekezaji and similar savings-and-investment groups.'],
        ],
    ],
    'agribusiness-financing-suite' => [
        'title' => 'AgriBusiness Financing Suite',
        'short_description' => 'Agricultural finance platform. Farmer loans, subsidies, crop insurance, and cooperative financing with digital farmer profiling for Tanzania.',
        'meta_description' => 'Agricultural finance software Tanzania. Farmer loans, cooperatives, crop insurance, subsidy management, AMCOS SACCO.',
        'meta_keywords' => 'agricultural finance Tanzania, farmer loan, AMCOS, crop insurance, cooperative financing',
        'icon' => 'tractor',
        'features' => [
            ['title' => 'Farmer profiling', 'description' => 'Digital profiles: land, crops, history, and creditworthiness to support loan and subsidy decisions.'],
            ['title' => 'Loan products', 'description' => 'Seasonal loans, input financing, equipment loans, and post-harvest finance with flexible repayment.'],
            ['title' => 'Cooperatives and AMCOS', 'description' => 'Support for cooperative structures, group lending, and linkage to AMCOS and buyers.'],
            ['title' => 'Subsidy and insurance', 'description' => 'Track subsidies and link to crop insurance or government programmes where applicable.'],
            ['title' => 'Mobile and field', 'description' => 'Field officer apps for registration and collection in areas with limited connectivity.'],
        ],
        'faqs' => [
            ['q' => 'Can we finance crop inputs?', 'a' => 'Yes. The suite supports input financing, seasonal loans, and repayment aligned with harvest and sales.'],
        ],
    ],
    'bot-rtsis-reporting' => [
        'title' => 'BOT RTSIS Reporting System',
        'short_description' => 'Automated Real-Time Supervisory Information System reporting for Bank of Tanzania. Accurate, audit-ready regulatory returns.',
        'meta_description' => 'BOT RTSIS reporting Tanzania. Bank of Tanzania supervisory reporting, automated returns, regulatory compliance, audit trail.',
        'meta_keywords' => 'BOT RTSIS Tanzania, bank supervisory reporting, BOT returns, regulatory reporting Tanzania',
        'icon' => 'shield-alt',
        'features' => [
            ['title' => 'Supervisory returns', 'description' => 'Automate submission of statistical and prudential returns required by the Bank of Tanzania.'],
            ['title' => 'Risk-based alignment', 'description' => 'Support for credit, liquidity, market, operational, and compliance risk data expected under BOT supervision.'],
            ['title' => 'Audit trail', 'description' => 'Full traceability from source systems to submitted returns for examinations and audits.'],
            ['title' => 'Scheduling and validation', 'description' => 'Scheduled runs and validation rules to reduce errors and meet reporting deadlines.'],
            ['title' => 'CAMELS support', 'description' => 'Data and reporting that support CAMELS and other supervisory assessments.'],
        ],
        'faqs' => [
            ['q' => 'What is RTSIS?', 'a' => 'RTSIS refers to the real-time supervisory information and reporting that banks and financial institutions submit to the Bank of Tanzania for off-site surveillance and risk monitoring.'],
            ['q' => 'Can we automate daily and monthly returns?', 'a' => 'Yes. The system can pull from core banking and other sources and generate returns on a daily, weekly, monthly, or ad hoc basis as required by BOT.'],
        ],
    ],
    'government-loans-eloans' => [
        'title' => 'Government Loans (eLoans)',
        'short_description' => 'Digital platform for government-backed loans. HESLB student loans, SME funds, and social welfare with verification and fraud prevention for Tanzania.',
        'meta_description' => 'Government loan platform Tanzania. HESLB student loans, SME funds, social welfare loans, verification, disbursement, recovery.',
        'meta_keywords' => 'HESLB Tanzania, government loans, student loans, SME fund, social welfare loan digital',
        'icon' => 'university',
        'features' => [
            ['title' => 'Eligibility and verification', 'description' => 'Verify applicants against government criteria (e.g. HESLB, SME, welfare). Reduce fraud with identity and data checks.'],
            ['title' => 'Disbursement', 'description' => 'Batch and individual disbursement to bank accounts or mobile money with audit trails.'],
            ['title' => 'Recovery and repayment', 'description' => 'Track repayments, arrears, and recovery. Integrate with payroll or employers where applicable.'],
            ['title' => 'Reporting to government', 'description' => 'Returns and reports for the sponsoring ministry or agency.'],
            ['title' => 'Transparency', 'description' => 'Clear status for beneficiaries and administrators. Compliant handling of personal data.'],
        ],
        'faqs' => [
            ['q' => 'Can this handle HESLB student loans?', 'a' => 'The platform can be configured for government-backed student and other loan programmes, including eligibility rules, disbursement, and recovery reporting.'],
        ],
    ],
    'contracts-documents-management' => [
        'title' => 'Contracts & Documents Management',
        'short_description' => 'Centralized document management. Contracts, legal and compliance records. E-signatures, version control, and approvals for Tanzania.',
        'meta_description' => 'Document management system Tanzania. Contracts, e-signatures, version control, compliance, legal documents.',
        'meta_keywords' => 'document management Tanzania, contract management, e-signature, compliance documents',
        'icon' => 'file-contract',
        'features' => [
            ['title' => 'Central repository', 'description' => 'Store contracts, policies, and compliance documents in one searchable, secure repository.'],
            ['title' => 'Version control', 'description' => 'Track versions and approvals. Know who signed what and when.'],
            ['title' => 'E-signatures and workflows', 'description' => 'Approval workflows and electronic signatures to speed up execution.'],
            ['title' => 'Access control', 'description' => 'Role-based access and audit logs for sensitive documents.'],
            ['title' => 'Compliance', 'description' => 'Retention and audit support for regulatory and internal compliance.'],
        ],
        'faqs' => [
            ['q' => 'Is e-signature legally valid in Tanzania?', 'a' => 'Electronic signatures are recognized under Tanzanian law for many contract types. The system supports audit trails to demonstrate consent and intent.'],
        ],
    ],
    'legal-cases-management' => [
        'title' => 'Legal Cases Management',
        'short_description' => 'Litigation tracking for banks and corporates. Court cases, legal risks, deadlines, and lawyer assignments in Tanzania.',
        'meta_description' => 'Legal case management Tanzania. Litigation tracking, court cases, deadlines, legal risk, law firm management.',
        'meta_keywords' => 'legal case management Tanzania, litigation tracking, court case management',
        'icon' => 'gavel',
        'features' => [
            ['title' => 'Case register', 'description' => 'Register and track cases by court, type, and status. Link documents and correspondence.'],
            ['title' => 'Deadlines and reminders', 'description' => 'Key dates, filings, and hearings with reminders so nothing is missed.'],
            ['title' => 'Cost and outside counsel', 'description' => 'Track legal spend and external lawyers. Budget and approval workflows.'],
            ['title' => 'Reporting', 'description' => 'Dashboards and reports for management and board on legal exposure and workload.'],
            ['title' => 'Confidentiality', 'description' => 'Access control and audit logs for privileged and sensitive information.'],
        ],
        'faqs' => [
            ['q' => 'Who is this for?', 'a' => 'Banks, insurers, and corporates with in-house legal or multiple outside firms who need one place to track cases, deadlines, and costs.'],
        ],
    ],
    'hr-management-system' => [
        'title' => 'HR Management System (HRMS)',
        'short_description' => 'Complete HR: recruitment, payroll, NSSF/WCF compliance, training, and performance. Tanzanian labour law compliant.',
        'meta_description' => 'HRMS Tanzania. Payroll, NSSF WCF, recruitment, leave, performance. Labour law compliant.',
        'meta_keywords' => 'HR software Tanzania, payroll NSSF WCF, HRMS, recruitment, labour law Tanzania',
        'icon' => 'id-card',
        'features' => [
            ['title' => 'Payroll and statutory', 'description' => 'Payroll with NSSF, WCF, PAYE, and other statutory deductions as per Tanzanian law.'],
            ['title' => 'Leave and attendance', 'description' => 'Leave types, balances, and attendance. Align with employment contracts and labour law.'],
            ['title' => 'Recruitment', 'description' => 'Vacancies, applications, and hiring workflow in one place.'],
            ['title' => 'Performance', 'description' => 'Goals, reviews, and appraisals. Support for probation and promotions.'],
            ['title' => 'Training and documents', 'description' => 'Training records and employee documents. Support for compliance and audits.'],
        ],
        'faqs' => [
            ['q' => 'Is NSSF and WCF included?', 'a' => 'Yes. The system is designed to calculate and report NSSF and WCF (and other statutory deductions) in line with Tanzanian requirements.'],
        ],
    ],
    'business-management-erp' => [
        'title' => 'Business Management ERP',
        'short_description' => 'ERP for SMEs in Tanzania. Finance, HR, sales, procurement, inventory. Real-time reporting and decision support.',
        'meta_description' => 'ERP Tanzania SME. Finance, HR, sales, procurement, inventory. Integrated business management.',
        'meta_keywords' => 'ERP Tanzania, SME business software, accounting, inventory, procurement',
        'icon' => 'building',
        'features' => [
            ['title' => 'Integrated modules', 'description' => 'Finance, inventory, sales, procurement, and HR in one system. Single source of truth.'],
            ['title' => 'Finance and reporting', 'description' => 'General ledger, receivables, payables, and financial reports. Support for local reporting standards.'],
            ['title' => 'Sales and procurement', 'description' => 'Quotes, orders, and purchase orders. Track suppliers and customers.'],
            ['title' => 'Inventory', 'description' => 'Stock levels, movements, and costing. Reduce overstock and stockouts.'],
            ['title' => 'Tanzania context', 'description' => 'Currency (TZS), tax (VAT, withholding), and reporting suited to Tanzanian SMEs.'],
        ],
        'faqs' => [
            ['q' => 'Is it suitable for small businesses?', 'a' => 'Yes. The ERP is designed for SMEs who need integrated finance, inventory, and operations without the complexity of large enterprise systems.'],
        ],
    ],
    'inventory-management-system' => [
        'title' => 'Inventory Management System',
        'short_description' => 'Digital inventory and asset management. Stock, fixed assets, procurement, and supplier payments with controls and audit trails.',
        'meta_description' => 'Inventory management Tanzania. Stock control, fixed assets, procurement, audit trail.',
        'meta_keywords' => 'inventory software Tanzania, stock management, fixed assets, procurement',
        'icon' => 'boxes',
        'features' => [
            ['title' => 'Stock management', 'description' => 'Receive, issue, transfer, and count. Min/max levels and reorder points.'],
            ['title' => 'Fixed assets', 'description' => 'Register assets, depreciation, and disposal. Support for audit and insurance.'],
            ['title' => 'Procurement', 'description' => 'Requisitions, POs, and supplier management. Approvals and audit trail.'],
            ['title' => 'Reporting', 'description' => 'Valuation, movement reports, and analytics for decision-making.'],
            ['title' => 'Controls', 'description' => 'User permissions and audit logs to protect assets and prevent fraud.'],
        ],
        'faqs' => [
            ['q' => 'Can we track multiple warehouses?', 'a' => 'Yes. The system supports multiple locations and transfers between them.'],
        ],
    ],
    'tenants-management-system' => [
        'title' => 'Tenants Management System',
        'short_description' => 'Property and rental management. Units, leases, rent collection, and maintenance. Mobile money for rent in Tanzania.',
        'meta_description' => 'Property management Tanzania. Rental management, lease tracking, rent collection, mobile money.',
        'meta_keywords' => 'property management Tanzania, rental software, tenant management, rent collection',
        'icon' => 'home',
        'features' => [
            ['title' => 'Properties and units', 'description' => 'Register properties, units, and lease terms. Track occupancy and renewals.'],
            ['title' => 'Rent collection', 'description' => 'Invoicing, due dates, and payment tracking. Integrate M-Pesa and bank for rent collection.'],
            ['title' => 'Maintenance', 'description' => 'Log requests, assign vendors, and track completion and cost.'],
            ['title' => 'Reporting', 'description' => 'Occupancy, arrears, and income reports for owners and managers.'],
            ['title' => 'Tenant portal', 'description' => 'Optional tenant self-service for statements and payments.'],
        ],
        'faqs' => [
            ['q' => 'Can tenants pay rent via M-Pesa?', 'a' => 'Yes. The system can be integrated with mobile money and bank channels so tenants pay rent electronically with automatic reconciliation.'],
        ],
    ],
    'incidents-management-system' => [
        'title' => 'Incidents Management System',
        'short_description' => 'IT and operational incident tracking. Log, assign, resolve with SLA management. Improve service delivery in Tanzania.',
        'meta_description' => 'Incident management Tanzania. IT support, SLA, ticketing, operational incidents.',
        'meta_keywords' => 'incident management Tanzania, IT ticketing, SLA, helpdesk',
        'icon' => 'exclamation-triangle',
        'features' => [
            ['title' => 'Log and track', 'description' => 'Capture incidents, categorize, and assign to teams. Track status until closure.'],
            ['title' => 'SLAs', 'description' => 'Define response and resolution SLAs. Escalate when at risk.'],
            ['title' => 'Knowledge base', 'description' => 'Link to solutions and runbooks. Reduce repeat incidents.'],
            ['title' => 'Reporting', 'description' => 'Volume, resolution time, and SLA compliance for continuous improvement.'],
            ['title' => 'Integration', 'description' => 'APIs and optional integration with monitoring and communication tools.'],
        ],
        'faqs' => [
            ['q' => 'Is this for IT only?', 'a' => 'It can be used for IT incidents, facilities, or any operational incidents where you need logging, assignment, and SLA tracking.'],
        ],
    ],
    'school-management-system' => [
        'title' => 'School Management System',
        'short_description' => 'School ERP for Tanzania. Student records, fees, academic reporting, and online payments. Nursery to higher education.',
        'meta_description' => 'School management software Tanzania. Student records, fee collection, academic reports, online payments.',
        'meta_keywords' => 'school management Tanzania, school ERP, fee collection, student records',
        'icon' => 'graduation-cap',
        'features' => [
            ['title' => 'Student lifecycle', 'description' => 'Admission, enrolment, classes, and transcripts. From nursery to secondary and beyond.'],
            ['title' => 'Fee management', 'description' => 'Fee structures, invoicing, and collection. M-Pesa and bank integration for parents.'],
            ['title' => 'Academic reporting', 'description' => 'Report cards, attendance, and performance. Support for NECTA and other boards.'],
            ['title' => 'Staff and timetables', 'description' => 'Teachers, subjects, and timetables. Leave and payroll where needed.'],
            ['title' => 'Parent communication', 'description' => 'SMS or in-app notifications for fees, attendance, and results.'],
        ],
        'faqs' => [
            ['q' => 'Can parents pay fees via M-Pesa?', 'a' => 'Yes. The system can integrate with mobile money and bank channels so parents pay school fees electronically.'],
            ['q' => 'Is it suitable for NECTA exams?', 'a' => 'Academic reporting and data can support preparation and submission for NECTA and similar boards.'],
        ],
    ],
    'zahanati-management-system' => [
        'title' => 'Zahanati Management System',
        'short_description' => 'Healthcare facility management. Patient records, billing, pharmacy, NHIF integration, and insurance claims for Tanzania.',
        'meta_description' => 'Hospital clinic software Tanzania. Patient records, billing, NHIF, pharmacy, insurance claims.',
        'meta_keywords' => 'hospital management Tanzania, clinic software, NHIF integration, patient records',
        'icon' => 'hospital',
        'features' => [
            ['title' => 'Patient records', 'description' => 'Registration, visits, diagnoses, and prescriptions. Electronic medical records.'],
            ['title' => 'Billing and NHIF', 'description' => 'Billing, NHIF claims, and other insurance. Reduce claim errors and delays.'],
            ['title' => 'Pharmacy and inventory', 'description' => 'Medicine stock, dispensing, and expiry. Link to prescriptions.'],
            ['title' => 'Appointments', 'description' => 'Scheduling and reminders. Reduce no-shows.'],
            ['title' => 'Reporting', 'description' => 'Clinical and financial reports for management and NHIF.'],
        ],
        'faqs' => [
            ['q' => 'Does it integrate with NHIF?', 'a' => 'The system is designed to support NHIF billing and claims. Specific integration depends on NHIF technical requirements and agreements.'],
        ],
    ],
    'events-management-system' => [
        'title' => 'Events Management System',
        'short_description' => 'Digital event management. Registration, contributions, vendors, and secure payments. Harambees, weddings, corporate events in Tanzania.',
        'meta_description' => 'Event management software Tanzania. Registration, contributions, harambee, wedding, corporate events, payments.',
        'meta_keywords' => 'event management Tanzania, harambee, contribution tracking, wedding events',
        'icon' => 'calendar-alt',
        'features' => [
            ['title' => 'Registration and invites', 'description' => 'Event setup, invitations, and registration. Track attendees and capacity.'],
            ['title' => 'Contributions', 'description' => 'Record cash and in-kind contributions. Transparent reporting for organisers and donors.'],
            ['title' => 'Vendors and budget', 'description' => 'Vendor list, costs, and payments. Stay within budget.'],
            ['title' => 'Payments', 'description' => 'Accept contributions via M-Pesa or bank. Secure and auditable.'],
            ['title' => 'Reporting', 'description' => 'Contribution lists, expenditure, and summaries for accountability.'],
        ],
        'faqs' => [
            ['q' => 'Is it suitable for harambees?', 'a' => 'Yes. The system supports contribution tracking, multiple payment channels, and transparent reporting—ideal for harambees, weddings, and community events.'],
        ],
    ],
    'notification-engine' => [
        'title' => 'Notification Engine',
        'short_description' => 'Centralised messaging. SMS, email, WhatsApp, and push. Campaigns and transactional alerts for Tanzania.',
        'meta_description' => 'Notification platform Tanzania. SMS, email, WhatsApp, push. Transactional and campaign messaging.',
        'meta_keywords' => 'SMS gateway Tanzania, WhatsApp notification, email SMS, notification platform',
        'icon' => 'bell',
        'features' => [
            ['title' => 'Multi-channel', 'description' => 'Send via SMS, email, WhatsApp, and push from one platform. Choose the right channel per message.'],
            ['title' => 'Transactional', 'description' => 'OTPs, alerts, and receipts. Templates and variables for personalisation.'],
            ['title' => 'Campaigns', 'description' => 'Schedule and send campaigns. Track delivery and engagement.'],
            ['title' => 'Tanzania networks', 'description' => 'SMS across Tanzanian networks. Reliable delivery and reporting.'],
            ['title' => 'API and integration', 'description' => 'REST API to trigger notifications from your core banking, CRM, or other systems.'],
        ],
        'faqs' => [
            ['q' => 'Which channels are supported?', 'a' => 'SMS, email, WhatsApp (Business API where available), and push notifications. Channels can be used alone or together.'],
            ['q' => 'Can we use it for OTP and alerts?', 'a' => 'Yes. The engine is built for transactional messages like OTPs, balance alerts, and payment confirmations, with templates and audit trails.'],
        ],
    ],
    'zona-ai' => [
        'title' => 'Zona AI – Intelligent Assistant',
        'short_description' => 'AI-powered virtual assistant. 24/7 support in Swahili and English, automated inquiries, and intelligent assistance for Tanzania.',
        'meta_description' => 'Zona AI assistant Tanzania. Swahili English, 24/7 customer support, chatbot, virtual assistant.',
        'meta_keywords' => 'AI assistant Tanzania, Swahili chatbot, customer support AI, Zona AI',
        'icon' => 'robot',
        'features' => [
            ['title' => 'Swahili and English', 'description' => 'Natural conversations in Swahili and English. Suited to Tanzanian customers and staff.'],
            ['title' => '24/7 availability', 'description' => 'Handle FAQs, account queries, and simple requests anytime. Escalate to humans when needed.'],
            ['title' => 'Integration', 'description' => 'Connect to your core systems, CRM, or knowledge base for accurate, up-to-date answers.'],
            ['title' => 'Customisable', 'description' => 'Train on your products and policies. Control tone and escalation rules.'],
            ['title' => 'Analytics', 'description' => 'See common questions and satisfaction to improve service and content.'],
        ],
        'faqs' => [
            ['q' => 'Does it really work in Swahili?', 'a' => 'Yes. Zona AI is designed to understand and respond in Swahili and English, making it suitable for Tanzanian customer bases.'],
            ['q' => 'Can it access our systems?', 'a' => 'It can be integrated with your APIs or knowledge base to provide accurate information (e.g. balance, status) within your security and compliance boundaries.'],
        ],
    ],
];
